import streamlit as st
import psutil
import time

def get_system_stats():
    # Memory Usage
    memory = psutil.virtual_memory()
    memory_percent = memory.percent
    memory_used_gb = memory.used / (1024 ** 3)
    memory_total_gb = memory.total / (1024 ** 3)

    # Disk Usage
    disk = psutil.disk_usage('/')
    disk_percent = disk.percent
    disk_used_gb = disk.used / (1024 ** 3)
    disk_total_gb = disk.total / (1024 ** 3)

    return {
        "memory_percent": memory_percent,
        "memory_used_gb": memory_used_gb,
        "memory_total_gb": memory_total_gb,
        "disk_percent": disk_percent,
        "disk_used_gb": disk_used_gb,
        "disk_total_gb": disk_total_gb
    }

st.set_page_config(page_title="Monolith-Core Health Dashboard", layout="wide")

st.title("Monolith-Core Health Dashboard")
st.markdown("### System Resource Monitoring")

if st.button("Refresh Data"):
    st.rerun()

stats = get_system_stats()

col1, col2 = st.columns(2)

with col1:
    st.header("Memory Usage")
    st.metric(label="RAM Usage", value=f"{stats['memory_percent']}%")
    st.progress(stats['memory_percent'] / 100)
    st.text(f"Used: {stats['memory_used_gb']:.2f} GB / {stats['memory_total_gb']:.2f} GB")

with col2:
    st.header("Disk Usage (C:)")
    st.metric(label="Disk Space", value=f"{stats['disk_percent']}%")
    st.progress(stats['disk_percent'] / 100)
    st.text(f"Used: {stats['disk_used_gb']:.2f} GB / {stats['disk_total_gb']:.2f} GB")

st.markdown("---")
st.caption("Auto-generated by Monolith-Core Agent")
