import os
import time
import hashlib
import random
from cognitive_router import CognitiveRouter

class GenesisEngine:
    """
    The Zenith Protocol.
    The true marker of a Sovereign System: the ability to write its own code
    and spawn new capabilities dynamically.
    """
    def __init__(self, target_dir="."):
        self.target_dir = target_dir
        self.generation_count = 0
        self.router = CognitiveRouter()

    def synthesize_agent(self, specific_trait="Tracker"):
        """Dynamically generates a new MonolithAgent python file to disk."""
        self.generation_count += 1
        
        # Give the mutant a unique hash DNA
        dna_hash = hashlib.sha256(str(time.time()).encode()).hexdigest()[:8]
        class_name = f"Mutant{specific_trait.capitalize()}_{dna_hash}"
        file_name = f"mutant_{specific_trait.lower()}_{dna_hash}.py"
        file_path = os.path.join(self.target_dir, file_name)

        # The Swarm uses the LLM to write Python
        llm_code = self.router.synthesize_agent_code(specific_trait, "High Volatility Crypto Market")
        
        if "failsafe" in llm_code.lower() or "class " not in llm_code:
            # Fallback to hardcoded template if the LLM is offline or hallucinated
            agent_code = f'''from monolith_agent import MonolithAgent
import time

class {class_name}(MonolithAgent):
    """
    Auto-generated by the Genesis Engine Template.
    Generation: {self.generation_count}
    Trait: {specific_trait}
    """
    def __init__(self):
        super().__init__("{class_name}")

    def run_cycle(self):
        self.logger.info("Mutant Agent [{class_name}] executing specialized {specific_trait} protocol...")
        self.log_action("Evolutionary Action", "Executing {specific_trait}")
'''
        else:
            # Dynamic LLM code insertion
            agent_code = llm_code.replace("```python", "").replace("```", "")
            # Ensure the class name matches our generated hash for import stability
            import re
            agent_code = re.sub(r'class \w+\(', f'class {class_name}(', agent_code)

        
        try:
            with open(file_path, "w") as f:
                f.write(agent_code)
            print(f"GENESIS ENGINE: New Agent Synthesized -> {file_path}")
            return class_name, file_path
        except Exception as e:
            print(f"GENESIS ENGINE Error: Failed to synthesize. {e}")
            return None, None
