import time
import random
import os
import json

# Revenue Bridge Integration
try:
    import sys
    sys.path.append(os.path.join(os.path.dirname(__file__), "..", ".."))
    from System.Revenue.gumroad_bridge import GumroadBridge
    GUMROAD_ENABLED = True
except ImportError:
    GUMROAD_ENABLED = False

def run_genesis_cycle():
    """
    The Asset Factory.
    Generates actual digital assets (files) to prove value creation.
    NOW UPGRADED: Can self-replicate by generating new Agent Code.
    """
    print("🏭 GENESIS ENGINE: INITIALIZING FACTORY...")
    
    # 1. Create Output Directories
    asset_dir = os.path.join(os.path.dirname(__file__), "..", "..", "Assets")
    agent_dir = os.path.join(os.path.dirname(__file__), "..", "Agents", "Generated")
    
    for d in [asset_dir, agent_dir]:
        if not os.path.exists(d):
            os.makedirs(d)
    
    # 2. Select Product Type
    products = [
        {"type": "BLOG_POST", "ext": ".md", "prefix": "article_"},
        {"type": "PYTHON_TOOL", "ext": ".py", "prefix": "tool_"},
        {"type": "DATA_SET", "ext": ".json", "prefix": "data_"},
        {"type": "NEW_AGENT", "ext": ".py", "prefix": "agent_"} # Self-Replication
    ]
    product = random.choice(products)
    
    # 3. Manufacture Asset
    timestamp = int(time.time())
    filename = f"{product['prefix']}{timestamp}{product['ext']}"
    
    # Determine Path
    filepath = os.path.join(agent_dir if product['type'] == "NEW_AGENT" else asset_dir, filename)
    
    print(f"   🔨 MANUFACTURING: {product['type']}...")
    time.sleep(1.5) # Production time
    
    content = ""
    if product['type'] == "BLOG_POST":
        content = f"# The Future of AI in 2026\n\nGenerated by Monolith Genesis.\n\nDate: {time.ctime()}..."
        
    elif product['type'] == "PYTHON_TOOL":
        content = f"# Monolith Auto-Tool\n# ID: {timestamp}\n\ndef quick_math(a, b):\n    return a * b\n"
        
    elif product['type'] == "DATA_SET":
        content = json.dumps({"id": timestamp, "market_sentiment": "BULLISH", "origin": "Genesis"})
        
    elif product['type'] == "NEW_AGENT":
        # WRITE A FULL AGENT CLASS
        agent_name = f"Agent_{timestamp}"
        content = f'''
import time
import random

class {agent_name}:
    """
    Autonomously generated by Genesis Engine.
    Purpose: Specialized Micro-Tasking.
    """
    def __init__(self):
        self.status = "BORN"
        self.id = "{timestamp}"
        
    def run_cycle(self):
        print(f"[{agent_name}] Alive and processing...")
        # Placeholder for emergent behavior
        return random.random()

if __name__ == "__main__":
    bot = {agent_name}()
    bot.run_cycle()
'''
        print(f"   🧬 BIOLOGY: SEQUENCING NEW AI DNA...")

    # 4. Save to Vault (Disk)
    with open(filepath, "w") as f:
        f.write(content)
        
    print(f"   ✅ ASSET COMPLETE: {filename}")
    if product['type'] == "NEW_AGENT":
        print(f"   🤖 NEW LIFEFORM CREATED: System/Agents/Generated/{filename}")
    else:
        print(f"   💰 ESTIMATED VALUE: ${random.uniform(5, 50):.2f}")
    
    # AUTO-PUBLISH TO GUMROAD (if configured)
    if GUMROAD_ENABLED and product['type'] in ['BLOG_POST', 'PYTHON_TOOL']:
        try:
            bridge = GumroadBridge()
            if bridge.is_configured():
                print(f"   📤 Auto-publishing to Gumroad...")
                result = bridge.auto_publish_genesis_output(filepath)
                
                if result.get("status") == "SUCCESS":
                    print(f"   ✅ LIVE: {result.get('url')}")
                    print(f"   💰 Price: ${result.get('price')}")
                else:
                    print(f"   ⚠️ Gumroad: {result.get('message')}")
        except Exception as e:
            print(f"   ⚠️ Gumroad error: {e}")
    
    return filepath

if __name__ == "__main__":
    run_genesis_cycle()
