"""
MONOLITH AGENT FACTORY v2.0
The Mother System.
Capabilities:
1. Spawns new agents from templates.
2. Registers agents in the core database.
3. HOT-SWAPS agents during runtime.
"""

import sys
import uuid
import json
import shutil
from pathlib import Path
from datetime import datetime

# Add System Root
ROOT = Path(__file__).parents[2]
sys.path.append(str(ROOT))

class AgentFactory:
    def __init__(self):
        self.root = ROOT
        self.agents_dir = self.root / "System" / "Agents" / "Active"
        self.agents_dir.mkdir(parents=True, exist_ok=True)
        self.registry_path = self.root / "System" / "Agents" / "registry.json"
        
        self.registry = self._load_registry()

    def _load_registry(self):
        if self.registry_path.exists():
            try:
                with open(self.registry_path, 'r') as f:
                    return json.load(f)
            except:
                pass
        return {}

    def _save_registry(self):
        with open(self.registry_path, 'w') as f:
            json.dump(self.registry, f, indent=2)

    def spawn_agent(self, agent_name, role, code_content=None):
        """
        Creates a new agent file.
        If code_content is None, uses a default template based on Role.
        """
        safe_name = agent_name.replace(" ", "_").lower()
        if not safe_name.endswith(".py"):
            safe_name += ".py"
            
        file_path = self.agents_dir / safe_name
        
        if file_path.exists():
            print(f"⚠️ [FACTORY] Agent {safe_name} already exists. Overwriting.")
            
        # 1. Determine Content
        if code_content:
            final_code = code_content
        else:
            final_code = self._get_template(role, agent_name)
            
        # 2. Write File
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(final_code)
            
        # 3. Register
        self.registry[safe_name] = {
            "id": str(uuid.uuid4()),
            "role": role,
            "created_at": datetime.now().isoformat(),
            "path": str(file_path.relative_to(self.root)),
            "status": "ACTIVE"
        }
        self._save_registry()
        
        print(f"🏭 [FACTORY] Spawned Agent: {safe_name} ({role})")
        return safe_name

    def _get_template(self, role, name):
        """Basic Templates"""
        base = f'''"""
MONOLITH AGENT: {name}
Role: {role}
Generated by AgentFactory
"""
import sys
import json
from pathlib import Path

ROOT = Path(__file__).parents[3]
sys.path.append(str(ROOT))

class {name.replace("_", " ").title().replace(" ", "")}:
    def __init__(self):
        self.root = ROOT
        
    def run(self, args=None):
        print(f"[{name.upper()}] 🚀 Running...")
        # LOGIC HERE
        return {{"status": "success"}}

if __name__ == "__main__":
    agent = {name.replace("_", " ").title().replace(" ", "")}()
    agent.run()
'''
        return base

if __name__ == "__main__":
    f = AgentFactory()
    f.spawn_agent("demo_factory_agent", "TEST", None)
